name: Docker Publish

# Triggers for the workflow
on:
  push:
    branches: [ "master" ]  # Trigger on push to master branch
    tags: [ 'v*.*.*' ]       # Trigger on semantic version tags like v1.0.0
  pull_request:
    branches: [ "master" ]   # Trigger on pull requests to master

env:
  REGISTRY: ghcr.io                      # GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }}    # Image name based on GitHub repo name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build and push backend image
      - name: Build backend Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest ./web-backend

      - name: Push backend Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest

      # Build and push frontend image
      - name: Build frontend Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest ./web-frontend

      - name: Push frontend Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
