name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]  # Trigger on push to master branch
    tags: [ 'v*.*.*' ]       # Trigger on semantic version tags like v1.0.0
  pull_request:
    branches: [ "master" ]   # Trigger on pull requests to master

env:
  REGISTRY: ghcr.io                      # GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }}    # Image name based on GitHub repo name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io  # GitHub Container Registry
      IMAGE_BACKEND: ${{ secrets.GITHUB_REPOSITORY }}/web-backend
      IMAGE_FRONTEND: ${{ secrets.GITHUB_REPOSITORY }}/web-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.GH_USERNAME }} --password-stdin

      # Build and Push web-backend Docker Image
      - name: Build web-backend Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:latest -f ./web-backend/Dockerfile ./web-backend

      - name: Push web-backend Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND }}:latest

      # Build and Push web-frontend Docker Image
      - name: Build web-frontend Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:latest -f ./web-frontend/Dockerfile ./web-frontend

      - name: Push web-frontend Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND }}:latest
